-- MySQL Script generated by MySQL Workbench
-- Seg 18 Nov 2019 09:19:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sistema03`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sistema03` (
  `idtable1` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `Valor_Renda` DECIMAL(10,2) NULL,
  `Valor_Despesa` DECIMAL(10,2) NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
